# Generated by Django 4.1 on 2022-08-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="performer",
            new_name="user",
        ),
    ]
