# Generated by Django 4.1 on 2022-08-11 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_tasklist_taskuser_user_tasks_for_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.AddField(
            model_name="task",
            name="user_task",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taskuser",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.task"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tasks_for_users",
            field=models.ManyToManyField(
                through="api.TaskUser", to="api.task"
            ),
        ),
        migrations.DeleteModel(
            name="TaskList",
        ),
    ]
