# Generated by Django 4.1 on 2022-08-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_task_user_task_task_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="tasks_for_users",
            field=models.ManyToManyField(
                related_name="user_id", through="api.TaskUser", to="api.task"
            ),
        ),
    ]
